"""
config.py — All bot settings. Edit this file or use a .env file.
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ── Telegram credentials ────────────────────────────────────────────────────
API_ID          = int(os.environ["API_ID"])
API_HASH        = os.environ["API_HASH"]
BOT_TOKEN       = os.environ["BOT_TOKEN"]
SESSION_STRING  = os.environ["SESSION_STRING"]   # generated by gen_session.py

# ── Optional: Spotify (for /play spotify:track:... or playlist links) ───────
SPOTIFY_CLIENT_ID     = os.getenv("SPOTIFY_CLIENT_ID", "")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET", "")

# ── Behaviour ───────────────────────────────────────────────────────────────
DEFAULT_VOLUME   = 100          # 0–200
MAX_QUEUE_SIZE   = 50           # max tracks per group
ADMIN_ONLY_CMDS  = True         # /stop /skip only usable by group admins
LOG_CHANNEL_ID   = int(os.getenv("LOG_CHANNEL_ID", "0"))  # 0 = disabled

# ── Vote-skip ────────────────────────────────────────────────────────────────
VOTESKIP_THRESHOLD = 0.5        # fraction of members needed (0.5 = majority)

# ── Radio ────────────────────────────────────────────────────────────────────
RADIO_AUTO_REFILL = True        # auto-seed more tracks when queue runs low
RADIO_REFILL_AT   = 3           # refill when queue drops below this many tracks

# ── Persistence ──────────────────────────────────────────────────────────────
AUTO_RESUME       = True        # attempt to resume queues after bot restart
HISTORY_LIMIT     = 20          # tracks shown by /history
